### ISSUE TITLE
Better README.md

### ISSUE THREAD

**Issue by klugier** [ismail-yilmaz/upp-components#5]
Hello Oblivion,

It seems that in top README.md there is not too many information. You should add at least the list of components and what they supposed to do. It will be much easier for the other people to localize what they want from your repository.

Of course good job with the components. I am gald you are part of our community!

Klugier

**Comment by ismail-yilmaz** [comment]
> It seems that in top README.md there is not too many information. You should add at least the list of components and what they supposed to do. It will be much easier for the other people to localize what they want from your repository.

Hello Klugier,

Noted. And this is my intention as well.

 I will:

- Move the (terminal) images in the CtrlLib/Images to -> imgur (to reduce the repo size)
- Convert all ReadMe files into markdown format.
- Fill in the top README file with useful information, such as packages list, short descriptions, repo version (in Upp format: 2020.2, etc.)

However, this has to wait a couple of weeks and the official release of Upp 2020.2,as I am very busy ATM.  :)

Best regards,
Oblivion

**Comment by mingodad** [comment]
Also how to use/install it in `theide`, I'm trying to figure out how to use it as a newbie and so far no idea:

Am I supposed to copy this project folders on top of `upp` installation ?

I'm looking through the `upp` to see if there is some clue there.

**Comment by mingodad** [comment]
Looking at https://www.ultimatepp.org/app$ide$PackagesAssembliesAndNests$en-us.html and playing with the first screen of `TheIDE` I found how:

Right click in the left panel  and select `New assembly..` and add the git cloned folder path in `Package nest` before the `upp` path.

Maybe adding this to the readme would help newbies like me !

Cheers !

**Comment by ismail-yilmaz** [comment]
@mingodad 


> Looking at https://www.ultimatepp.org/app$ide$PackagesAssembliesAndNests$en-us.html and playing with the first screen of `TheIDE` I found how:
> 
> Right click in the left panel and select `New assembly..` and add the git cloned folder path in `Package nest` before the `upp` path.
> 
> Maybe adding this to the readme would help newbies like me !


Sorry for the missing information. I've been very busy for the last couple of months, but I'll update the README, within this week. In the meantime, If you encounter any problems or have questions let me know. 

You can set the repo as a Upp nest or simply copy the packages into `uppsrc` or `bazaar` (or where TheIDE can find them)

Best regards,

**Comment by mingodad** [comment]
Thanks for reply !
As I mentioned I just add it as a nest and trying to build the `TerminalExample` I'm getting this message:
```
upp-components/Examples/TerminalExample/main.cpp (1): fatal error: Terminal/Terminal.h: No such file or directory

```
It seems that the `Terminal` package is there but maybe the path is incorrect because when I click on it in the left panel of `TheIDE` nothing is shown.

Cheers !

**Comment by mingodad** [comment]
Removing the `Terminal` package and adding again and also changing the include path in main.cpp from `#include <Terminal/Terminal.h>` to `#include <CtrlLib/Terminal/Terminal.h>` now I can build and execute it.

It seems that you did a reorganization of the folders but didn't update the example projects.

**Comment by ismail-yilmaz** [comment]
@mingodad 
> Thanks for reply !
> As I mentioned I just add it as a nest and trying to build the `TerminalExample` I'm getting this message:
> 
> ```
> upp-components/Examples/TerminalExample/main.cpp (1): fatal error: Terminal/Terminal.h: No such file or directory
> ```
> 
> It seems that the `Terminal` package is there but maybe the path is incorrect because when I click on it in the left panel of `TheIDE` nothing is shown.
> 
> Cheers !

For the sake of simplicity, and since you are simply trying to test stuff (and until you get a better grasp of U++ nest/assembly concepts, which can be confusing sometimes), I suggest you drop the `Terminal` folder intto `uppsrc` and the `TerminalExample` folder intto uppsrc/examples and try again from there. It should normally work.

**Comment by ismail-yilmaz** [comment]
@mingodad

> Removing the `Terminal` package and adding again and also changing the include path in main.cpp from `#include <Terminal/Terminal.h>` to `#include <CtrlLib/Terminal/Terminal.h>` now I can build and execute it.
> 
> It seems that you did a reorganization of the folders but didn't update the example projects.

Not quite right.

The usual way is to create an assembly called `upp-components` in TheIDE's main package selection screen.
And setting the relevant paths to it (order is important):

```
/home/myuser/mypath/upp-components/Examples
/home/myuser/mypath/upp-components/CtrlLib
/home/myuser/mypath/uppsrc/
```

This can be further configured or partitioned but, as I mentioned above, you need to understand nests and assemblies.

Best regards,

**Comment by mingodad** [comment]
Thank you !
That made it work as you intended.
I think that is what should be added to the readme.

**Comment by ismail-yilmaz** [comment]
> Thank you !
> That made it work as you intended.
> I think that is what should be added to the readme.

I will, bu we hopefully won't need that from 2021.1 release and on, as the U++ team (or Mirek, really) is developing the UppHub framework where TheIDE will automatically download and setup git/svn repos as nests or assemblies for us. :)

Again, if you encounter any problems or have more questions let me know. (You can use the issue tracker or use the Upp forums.)

Best regards,

**Comment by ismail-yilmaz** [comment]
I have updated the README file and tagged the `upp-components` repo as 2020.2.
