### ISSUE TITLE
About copy

### ISSUE THREAD

**Issue by chivstyle** [ismail-yilmaz/upp-components#8]
```
U++: upp-win-15400
Toolchain: MSVS19x64
OS: Windows 10 64bits
```
You added a linebreak even the selected text is only a single line. I think that's not what we expected at most situations. For example:

I want to input something like below:
```
export LD_LIBRARY_PATH=$(pwd)/lib:$LD_LIBRARY_PATH:/$(pwd)/last/lib
```

```
export LD_LIBRARY_PATH=$(pwd)/lib:$
```
Now, I copy the ```LD_LIBRARY_PATH```, that's not the last text absolutely, I want to input more chars later, but the '\r'
will break the work.

**Comment by ismail-yilmaz** [comment]
Fix attempt: 80fb5e42e98bf85bf795b4ceffbabbf81e7a32f7

Text selection/copy should behave as expected now. Please check.
